### ISSUE TITLE
Ashstone and Dragonstone drop ores not their gems

### ISSUE THREAD

**Issue by Dubster94** [Sinhika/Netherrocks#6] opened 2017-05-03 17:41 UTC
Ashstone and Dragonstone ores when mined drop their ore blocks. Looking at SimpleOres wikis of the past, this used to not be the case and they would drop their gems instead. Of course, if it is your intention then so be it. I simply find it quite confusing as all gem ores are otherwise dropped as gems.

**Comment by Sinhika** [comment] 2017-05-11 18:54
I will look into this. The gem drop may have been missed when porting, as it's setup in the config code (a silly place to put it, and I am fixing that). If the gem drop was missed, than what you are getting is what was intended to be the result of using Silk Touch: an ore block you could smelt to get the gems, like what happens with diamond ore and emerald ore if you Silk Touch them and smelt.

**Comment by Sinhika** [comment] 2017-09-04 19:00
Fixed with commit 6beade5d4f9c1946210a1b7ded0ee9af7b2bde0f  for 1.11.2.

**Closed as completed by Sinhika** 2017-09-04 19:00 UTC
Labels: bug
