### ISSUE TITLE
Crash While Loading and Charcoal from trees

### ISSUE THREAD

**Issue by Ravin26** [Sinhika/Netherrocks#17] opened 2021-09-01 00:31 UTC
It seemed like for some reason this mod was making it so that breaking a tree gave you charcoal instead of wood. To make sure this was the mod causing it I made a test 1.17.1 modpack with just your mod and SimpleCore Lib. While loading the game I got this crash report. 
[crash-2021-08-31_20.21.14-client.txt](https://github.com/Sinhika/Netherrocks/files/7087414/crash-2021-08-31_20.21.14-client.txt)

**Comment by Sinhika** [comment] 2021-09-01 01:40
Breaking a tree with anything, or with particular tools? It's only supposed to auto-smelt with fyrite tools. If a fyrite axe harvests charcoal instead of wood, that's an intended feature, not a bug.  If some other axe harvests charcoal, that's a bug.

The crash is a separate problem that I am working on fixing. It is caused by the Netherrocks code being dependent on certain JEI API classes, even with JEI isn't loaded. That's my mistake, not isolating the JEI-dependent code enough. The quickie workaround until I get a fix out is to install the "Just Enough Items" mod.

**Comment by Ravin26** [comment] 2021-09-01 01:43
I was using a stone axe and thanks I’ll download JEI.

**Comment by Ravin26** [comment] 2021-09-01 01:54
I tested it out with just Netherrocks and its dependancies. It seems to be happening no matter what I use to break it.

**Comment by Sinhika** [comment] 2021-09-01 22:39
Yes, agreed, I confirmed it myself. That's a weird one, because the exact same code worked fine in 1.15.2 & 1.16.5. Forge may have broken something, or Minecraft broke something, and it may take me a while to chase it down.

This is a serious enough bug that I may need to suspend that feature of Fyrite until I can fix it, or work around it.

**Comment by Ravin26** [comment] 2021-09-01 22:44
Good luck with figuring out the issue. I’ll download it again when it’s fixed. Thanks for helping me out.

**Comment by Sinhika** [comment] 2021-09-02 02:42
Figured it out (see commit c4c1b0faddabf6f6c9a7a59dc481041443270761).
Fixed with release 1.17.1-3.0.0.4.

**Closed as completed by Sinhika** 2021-09-02 02:42 UTC
